version: '3'
services:
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 10000:10000/tcp
      - 8000:8000/tcp
    environment:
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - /home/ubuntu/environment/compartida:/compartida
      